version: "3.8"

services:
  database:
    image: mongo:6.0.2-focal
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    restart: always
  backend:
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - archives:/usr/src/app/archives
    depends_on:
      - database
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URI: mongodb://database
      PORT: 3001
  frontend:
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    restart: always

volumes:
  data:
  archives:
